### ISSUE TITLE
broken ftp links on BRACS dataset website

### ISSUE THREAD

**Issue by eliramnof** [histocartography/hact-net#3]
Trying to download any of the three datasets (WSI, ROI or Annotations) on the download site (https://www.bracs.icar.cnr.it/download/) returns the following errors using `wget`: 

--2021-11-04 13:14:21--  ftp://histoimage.na.icar.cnr.it/BRACS_WSI
           => ‘BRACS_WSI’
Resolving histoimage.na.icar.cnr.it (histoimage.na.icar.cnr.it)... 140.164.14.51
Connecting to histoimage.na.icar.cnr.it (histoimage.na.icar.cnr.it)|140.164.14.51|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD not needed.
==> SIZE BRACS_WSI ... done.

==> PASV ... done.    ==> RETR BRACS_WSI ... 
No such file ‘BRACS_WSI’.

**Comment by guillaumejaume** [comment]
What's the exact command line and OS you're using? 

Running: `wget -r 'ftp://histoimage.na.icar.cnr.it/BRACS_WSI_Annotations/'` on my Mac works as expected.

Guillaume

**Comment by eliramnof** [comment]
thanks for the quick response, I tried that (also on mac) and it works fine. 

Clicking on the links directly in the browser and logging in as 'guest' mounts empty folders so I thought there may be a naming issue in the server.

**Comment by guillaumejaume** [comment]
Glad it works now.
